# Generated by Django 6.0 on 2026-03-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='Porcentaje de descuento'),
        ),
    ]
